from __future__ import annotations

from fu_gm.models import Affinity, EffectTiming, SpellDefinition, SpellEffectType, SpellTarget, StatusEffect


SPELLS: dict[str, SpellDefinition] = {
    "落雷": SpellDefinition(
        name="落雷",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=5,
        damage_type="lightning",
        defense_type="magic",
        description="以雷击轰击单体目标。",
    ),
    "火焰弹": SpellDefinition(
        name="火焰弹",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=5,
        damage_type="fire",
        defense_type="magic",
        description="以火焰爆裂轰击单体目标。",
    ),
    "雷暴放射": SpellDefinition(
        name="雷暴放射",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=7,
        damage_type="lightning",
        defense_type="magic",
        description="将过载雷流集中射向单体目标。",
    ),
    "魔导屏障": SpellDefinition(
        name="魔导屏障",
        mp_cost=8,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.DEFENSE_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        defense_bonus={"physical": 2, "magic": 2},
        description="展开持续到场景结束的魔导护壁。",
    ),
    "守护咏唱": SpellDefinition(
        name="守护咏唱",
        mp_cost=6,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.DEFENSE_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.OWNER_TURN_START,
        defense_bonus={"physical": 2, "magic": 2},
        description="在目标身上维持到施法者下回合开始的短暂护佑。",
    ),
    "元素护体": SpellDefinition(
        name="元素护体",
        mp_cost=8,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.AFFINITY_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        affinity_changes={"lightning": Affinity.RESIST},
        description="让目标直到场景结束前对雷系伤害获得抗性。",
    ),
    "元素防护罩": SpellDefinition(
        name="元素防护罩",
        mp_cost=5,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.AFFINITY_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("wind", "lightning", "earth", "fire", "ice"),
        description="选择一种元素伤害，让目标在场景中对其获得抗性。",
    ),
    "元素武器": SpellDefinition(
        name="元素武器",
        mp_cost=10,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.WEAPON_ENCHANT,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("wind", "lightning", "earth", "fire", "ice"),
        description="将一件武器附着为指定元素属性。",
    ),
    "照明烈焰": SpellDefinition(
        name="照明烈焰",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=25,
        damage_type="fire",
        defense_type="magic",
        ignore_resist=True,
        description="高温火光贯穿防御，对单体造成强力火伤。",
    ),
    "电流术": SpellDefinition(
        name="电流术",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="lightning",
        defense_type="magic",
        status_effect=StatusEffect.DAZED,
        description="以电流轰击目标，大成功时令其眩晕。",
    ),
    "冰川覆裂": SpellDefinition(
        name="冰川覆裂",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="ice",
        defense_type="magic",
        status_effect=StatusEffect.SLOW,
        description="以寒霜冻结目标，大成功时令其迟缓。",
    ),
    "冰冻堡垒": SpellDefinition(
        name="冰冻堡垒",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=25,
        damage_type="ice",
        defense_type="magic",
        ignore_resist=True,
        description="用冰柱封锁目标，对单体造成强力冰伤。",
    ),
    "伊格尼斯之火": SpellDefinition(
        name="伊格尼斯之火",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="fire",
        defense_type="magic",
        status_effect=StatusEffect.SHAKEN,
        description="以灼热火焰灼烧目标，大成功时令其动摇。",
    ),
    "大地震击": SpellDefinition(
        name="大地震击",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="earth",
        defense_type="magic",
        status_effect=StatusEffect.SLOW,
        description="以大地尖刺冲击目标，大成功时令其迟缓。",
    ),
    "雷霆": SpellDefinition(
        name="雷霆",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=25,
        damage_type="lightning",
        defense_type="magic",
        ignore_resist=True,
        description="以粗暴闪电击穿目标，对单体造成强力雷伤。",
    ),
    "烈风": SpellDefinition(
        name="烈风",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="wind",
        defense_type="magic",
        description="以风刃撕裂目标。",
    ),
    "光环": SpellDefinition(
        name="光环",
        mp_cost=5,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.DEFENSE_FLOOR,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        defense_floor={"magic": 12},
        description="让目标的魔防至少视为 12。",
    ),
    "觉醒": SpellDefinition(
        name="觉醒",
        mp_cost=20,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.ATTRIBUTE_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_attributes=("DEX", "INS", "MIG", "WLP"),
        description="让目标选择的一项属性临时提升一个骰阶。",
    ),
    "护盾": SpellDefinition(
        name="护盾",
        mp_cost=5,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.DEFENSE_FLOOR,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        defense_floor={"physical": 12},
        description="让目标的物防至少视为 12。",
    ),
    "净化": SpellDefinition(
        name="净化",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_CLEAR,
        attributes=["INS", "WLP"],
        clear_all_statuses=True,
        description="清除目标身上的全部异常状态。",
    ),
    "激怒": SpellDefinition(
        name="激怒",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        status_effect=StatusEffect.ENRAGED,
        description="扰乱目标心绪，使其陷入激怒。",
    ),
    "幻觉": SpellDefinition(
        name="幻觉",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        selectable_statuses=(StatusEffect.DAZED, StatusEffect.SHAKEN),
        description="制造可怕幻觉，使目标陷入眩晕或动摇。",
    ),
    "治愈": SpellDefinition(
        name="治愈",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.HEAL,
        attributes=["INS", "WLP"],
        fixed_damage=40,
        description="治疗目标的伤势与疲劳。",
    ),
    "光照射线": SpellDefinition(
        name="光照射线",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="light",
        defense_type="magic",
        status_effect=StatusEffect.DAZED,
        description="以纯净灵光灼烧目标，大成功时令其眩晕。",
    ),
    "慈悲": SpellDefinition(
        name="慈悲",
        mp_cost=20,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.SURVIVE_ONCE,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        survive_at_one=True,
        description="目标本场景中第一次将要倒下时保留 1 点 HP。",
    ),
    "加强": SpellDefinition(
        name="加强",
        mp_cost=5,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.STATUS_IMMUNITY,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_statuses=(
            StatusEffect.DAZED,
            StatusEffect.ENRAGED,
            StatusEffect.POISONED,
            StatusEffect.SHAKEN,
            StatusEffect.SLOW,
            StatusEffect.WEAKENED,
        ),
        description="令目标在场景中免疫一种选定的异常状态。",
    ),
    "灵魂武器": SpellDefinition(
        name="灵魂武器",
        mp_cost=10,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.WEAPON_ENCHANT,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        weapon_damage_type="light",
        description="让一件武器在场景内转为光属性。",
    ),
    "迟钝": SpellDefinition(
        name="迟钝",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        selectable_statuses=(StatusEffect.SLOW, StatusEffect.WEAKENED),
        description="阻断目标体内灵力，使其迟缓或虚弱。",
    ),
    "加速": SpellDefinition(
        name="加速",
        mp_cost=20,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.EXTRA_ACTION,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        extra_actions=2,
        description=(
            "在目标每个回合结束时，可选择用装备武器顺势攻击，或顺势施放总 MP 消耗不高于 10 的法术。"
            "目标从单次法术中第二次获得增益后，此法术结束。"
        ),
    ),
    "黑暗武器": SpellDefinition(
        name="黑暗武器",
        mp_cost=10,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.WEAPON_ENCHANT,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        weapon_damage_type="dark",
        description="让一件武器在场景内转为暗属性。",
    ),
    "消除": SpellDefinition(
        name="消除",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DISPEL,
        attributes=["INS", "WLP"],
        description="驱散目标当前承受的所有法术效果。",
    ),
    "抽取精魂": SpellDefinition(
        name="抽取精魂",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.MP_DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        defense_type="magic",
        drain_to="mp",
        description="吞噬目标灵魂能量，夺取其 MP 并将一部分化为己用。",
    ),
    "抽取活力": SpellDefinition(
        name="抽取活力",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="dark",
        defense_type="magic",
        drain_to="hp",
        description="吞噬目标生命力，对其造成暗伤并吸收部分生命。",
    ),
}

CANONICAL_SPELLS: dict[str, SpellDefinition] = {
    # 元素使
    "巨岩": SpellDefinition(
        name="巨岩",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="earth",
        defense_type="magic",
        ignore_resist=True,
        description="你召唤一块巨大的岩石，使其砸向你的敌人。你对目标造成【高值+15】的土系伤害，此法术造成的伤害无视抵抗相性。",
    ),
    "元素幕障": SpellDefinition(
        name="元素幕障",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.AFFINITY_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("wind", "lightning", "ice", "fire", "earth"),
        description="选择风、雷、冰、火或土；至多三个目标直到场景结束前对所选伤害类型获得抵抗相性。",
    ),
    "焰流": SpellDefinition(
        name="焰流",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=25,
        damage_type="fire",
        defense_type="magic",
        ignore_resist=True,
        description="发射高温火焰射线，对单体造成【HR+25】火系伤害，且无视抵抗相性。",
    ),
    "闪电击": SpellDefinition(
        name="闪电击",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="lightning",
        defense_type="magic",
        status_effect=StatusEffect.DAZED,
        description="以轰鸣闪电攻击目标，造成【HR+15】雷系伤害。机会：所有被命中的目标受到眩晕。",
    ),
    "寒霜术": SpellDefinition(
        name="寒霜术",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="ice",
        defense_type="magic",
        status_effect=StatusEffect.SLOW,
        description="以厚重寒霜包裹目标，造成【HR+15】冰系伤害。机会：所有被命中的目标受到迟缓。",
    ),
    "冰山术": SpellDefinition(
        name="冰山术",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=25,
        damage_type="ice",
        defense_type="magic",
        ignore_resist=True,
        description="以魔法冰柱困住敌人，对单体造成【HR+25】冰系伤害，且无视抵抗相性。",
    ),
    "炎弹": SpellDefinition(
        name="炎弹",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="fire",
        defense_type="magic",
        status_effect=StatusEffect.SHAKEN,
        description="召出火焰弹幕轰击敌人，造成【HR+15】火系伤害。机会：所有被命中的目标受到动摇。",
    ),
    "翱翔击": SpellDefinition(
        name="翱翔击",
        mp_cost=10,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        description="你立即使用当前装备的一件近战武器进行顺势攻击；可攻击通常只能被远程攻击选中的目标。格斗、矛或剑类武器额外造成 5 点伤害；命中飞行目标可迫使其落地。",
    ),
    "地动": SpellDefinition(
        name="地动",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="earth",
        defense_type="magic",
        opportunity_turn_penalty=1,
        description="嶙峋岩柱破土而出，对目标造成【HR+15】土系伤害；不能选择飞行、漂浮、坠落或半空中的生物。机会：被命中生物下回合少执行一次行动。",
    ),
    "雷霆击": SpellDefinition(
        name="雷霆击",
        mp_cost=20,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=25,
        damage_type="lightning",
        defense_type="magic",
        ignore_resist=True,
        description="劈下一道闪电，对单体造成【HR+25】雷系伤害，且无视抵抗相性。",
    ),
    "罡风": SpellDefinition(
        name="罡风",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="wind",
        defense_type="magic",
        opportunity_ground_flying=True,
        description="召唤风力撕裂敌人，造成【HR+15】风系伤害。机会：被命中的飞行生物被迫立刻落地。",
    ),
    "气旋": SpellDefinition(
        name="气旋",
        mp_cost=10,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.DEFENSE_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        defense_bonus={"physical": 2},
        description="呼啸阵风包围你；在受到远程攻击时物防 +2，持续到场景结束。系统以场景内物防 +2 记录，远程限定由 GM 裁量。",
    ),
    # 熵术士
    "加速术": SpellDefinition(
        name="加速术",
        mp_cost=20,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.EXTRA_ACTION,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        extra_actions=2,
        description="在目标每个回合结束时，可选择用装备武器顺势攻击，或顺势施放总 MP 消耗不高于 10 的法术。目标从单次法术中第二次获得增益后，此法术结束。",
    ),
    "扭曲性状": SpellDefinition(
        name="扭曲性状",
        mp_cost=20,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        description="若目标受到原本会被其吸收或免疫的伤害类型，则改视为该类型弱点；触发后法术立即结束。",
    ),
    "黑暗武器": SpellDefinition(
        name="黑暗武器",
        mp_cost=5,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.WEAPON_ENCHANT,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        weapon_damage_type="dark",
        description="将黑暗能量注入一件已装备武器，使其伤害变为暗系；若施放时正装备该武器，可用其顺势攻击。",
    ),
    "驱散魔法": SpellDefinition(
        name="驱散魔法",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DISPEL,
        attributes=["INS", "WLP"],
        description="净化目标承受的所有持续时间为场景的法术效果。",
    ),
    "预言术": SpellDefinition(
        name="预言术",
        mp_cost=10,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        description="在法术结束前，你看见的生物进行非大成功/非大失败检定后，你可强迫其重掷两枚骰子；强制重掷两次后法术结束。",
    ),
    "精神汲取": SpellDefinition(
        name="精神汲取",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.MP_DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=20,
        defense_type="magic",
        drain_to="mp",
        description="目标失去【HR+20】MP；随后你恢复其本次损失 MP 的一半。若目标 MP 归零，你不会恢复 MP。",
    ),
    "活力汲取": SpellDefinition(
        name="活力汲取",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="dark",
        defense_type="magic",
        drain_to="hp",
        description="对目标造成【HR+15】暗系伤害；随后你恢复其本次损失 HP 的一半。若目标 HP 归零，你不会恢复 HP。",
    ),
    "无常命运": SpellDefinition(
        name="无常命运",
        mp_cost=10,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        description="消耗至多 20 MP；每 10 MP 掷一个当前 WLP 骰，保留一枚并按点数触发混沌效果：自损、全场中毒/迟缓、至多三目标恢复并清异常，或任选多目标造成随机类型 30 点伤害。",
    ),
    "镜面反射": SpellDefinition(
        name="镜面反射",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        description="目标被攻击性法术选中时，施法者改为选中自身为目标；其他目标不变。触发后此法术结束。",
    ),
    "终焉降临": SpellDefinition(
        name="终焉降临",
        mp_cost=15,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        description="目标失去 20+目标等级一半的 HP。此为固定 HP 损失，需由 GM 或硬规则按目标等级结算。",
    ),
    "时空静滞": SpellDefinition(
        name="时空静滞",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.NARRATIVE,
        attributes=["INS", "WLP"],
        description="目标在自身下个回合中少执行一次行动，行动次数最低为 0。",
    ),
    "影袭": SpellDefinition(
        name="影袭",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="dark",
        defense_type="magic",
        status_effect=StatusEffect.WEAKENED,
        description="黑暗能量风暴将物质化作飞灰，造成【HR+15】暗系伤害。机会：所有被命中的目标受到虚弱。",
    ),
    # 御魂使
    "护卫灵气": SpellDefinition(
        name="护卫灵气",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DEFENSE_FLOOR,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        defense_floor={"magic": 12},
        description="目标在被任何效果选为目标时，魔防视为至少 12；20 级为 13，40 级为 14。",
    ),
    "屏障": SpellDefinition(
        name="屏障",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DEFENSE_FLOOR,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        defense_floor={"physical": 12},
        description="目标在被任何效果选为目标时，物防视为至少 12；20 级为 13，40 级为 14。",
    ),
    "治愈术": SpellDefinition(
        name="治愈术",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.HEAL,
        attributes=["INS", "WLP"],
        fixed_damage=40,
        description="每个目标恢复 40 HP；20 级恢复 50，40 级恢复 60。",
    ),
    "光耀术": SpellDefinition(
        name="光耀术",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="light",
        defense_type="magic",
        status_effect=StatusEffect.DAZED,
        description="将内在能量化为耀眼魂弹，造成【HR+15】光系伤害。机会：所有被命中的目标受到眩晕。",
    ),
    "巩固": SpellDefinition(
        name="巩固",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_IMMUNITY,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_statuses=(
            StatusEffect.SLOW,
            StatusEffect.SHAKEN,
            StatusEffect.WEAKENED,
            StatusEffect.DAZED,
            StatusEffect.ENRAGED,
            StatusEffect.POISONED,
        ),
        description="从迟缓、动摇、虚弱、眩晕、激怒或中毒中选择其一；目标直到场景结束前免疫所选异常。",
    ),
    "灵魂之幕": SpellDefinition(
        name="灵魂之幕",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.AFFINITY_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("dark", "light", "poison"),
        description="选择暗、光或毒；目标直到场景结束前对所选伤害类型获得抵抗相性。",
    ),
    "魂能武器": SpellDefinition(
        name="魂能武器",
        mp_cost=5,
        target=SpellTarget.ONE_ALLY,
        effect_type=SpellEffectType.WEAPON_ENCHANT,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        weapon_damage_type="light",
        description="将一件武器注入净化灵魂能量，使其伤害变为光系；若施放时正装备该武器，可用其顺势攻击。",
    ),
    "怠惰": SpellDefinition(
        name="怠惰",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        selectable_statuses=(StatusEffect.SLOW, StatusEffect.WEAKENED),
        description="压制敌人体内灵魂能量；选择迟缓或虚弱，所有被命中的目标受到所选异常。",
    ),
}

SPELLS.update(CANONICAL_SPELLS)


# These are the generic NPC spells from the core rulebook (pp. 310-311).
# They intentionally live outside ``SPELL_SCHOOLS``: PCs cannot learn them
# through Elemental Magic, Entropic Magic, or Spirit Magic.
NPC_SPELLS: dict[str, SpellDefinition] = {
    "范围异常": SpellDefinition(
        name="范围异常",
        mp_cost=20,
        target=SpellTarget.ANY_VISIBLE_CREATURES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        selectable_statuses=(
            StatusEffect.SLOW,
            StatusEffect.SHAKEN,
            StatusEffect.WEAKENED,
            StatusEffect.DAZED,
        ),
        automatic_effect=True,
        mp_cost_per_target=False,
        description="选择任意数量可见生物，并对每个目标施加所选的一种异常状态。",
    ),
    "吐息": SpellDefinition(
        name="吐息",
        mp_cost=5,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=10,
        defense_type="magic",
        selectable_damage_types=(
            "physical",
            "wind",
            "lightning",
            "dark",
            "earth",
            "fire",
            "ice",
            "light",
            "poison",
        ),
        description="对目标造成【高值+10】的所选类型伤害。",
    ),
    "诅咒": SpellDefinition(
        name="诅咒",
        mp_cost=5,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        selectable_statuses=(
            StatusEffect.SLOW,
            StatusEffect.SHAKEN,
            StatusEffect.WEAKENED,
            StatusEffect.DAZED,
        ),
        description="对目标施加所选的一种异常状态。",
    ),
    "恶毒诅咒": SpellDefinition(
        name="恶毒诅咒",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        selectable_statuses=(
            StatusEffect.SLOW,
            StatusEffect.SHAKEN,
            StatusEffect.WEAKENED,
            StatusEffect.DAZED,
        ),
        selectable_status_count=2,
        description="对目标施加所选的两种不同异常状态。",
    ),
    "诅咒吐息": SpellDefinition(
        name="诅咒吐息",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        defense_type="magic",
        selectable_damage_types=(
            "physical",
            "wind",
            "lightning",
            "dark",
            "earth",
            "fire",
            "ice",
            "light",
            "poison",
        ),
        selectable_statuses=(
            StatusEffect.SLOW,
            StatusEffect.SHAKEN,
            StatusEffect.WEAKENED,
            StatusEffect.DAZED,
        ),
        apply_status_on_success=True,
        description="对目标造成【高值+15】的所选类型伤害，并施加所选的一种异常状态。",
    ),
    "毁灭": SpellDefinition(
        name="毁灭",
        mp_cost=30,
        target=SpellTarget.ALL_ENEMIES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=30,
        selectable_damage_types=(
            "physical",
            "wind",
            "lightning",
            "dark",
            "earth",
            "fire",
            "ice",
            "light",
            "poison",
        ),
        automatic_effect=True,
        fixed_damage_only=True,
        mp_cost_per_target=False,
        minimum_level=30,
        allowed_npc_ranks=("elite", "champion"),
        npc_last_turn_only=True,
        description="对施法者能看见的每个敌人造成30点所选类型伤害。",
    ),
    "舔舐伤口": SpellDefinition(
        name="舔舐伤口",
        mp_cost=5,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.HEAL,
        attributes=["INS", "WLP"],
        fixed_damage=20,
        description="恢复20点生命值；20/40/60级时改为30/40/50点。",
    ),
    "偷取生命": SpellDefinition(
        name="偷取生命",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        defense_type="magic",
        selectable_damage_types=(
            "physical",
            "wind",
            "lightning",
            "dark",
            "earth",
            "fire",
            "ice",
            "light",
            "poison",
        ),
        drain_to="hp",
        drain_requires_target_above_zero=False,
        description="造成【高值+15】的所选类型伤害，并恢复所造成总伤害量一半的生命值。",
    ),
    "偷取精神": SpellDefinition(
        name="偷取精神",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        defense_type="magic",
        selectable_damage_types=(
            "physical",
            "wind",
            "lightning",
            "dark",
            "earth",
            "fire",
            "ice",
            "light",
            "poison",
        ),
        drain_to="mp",
        drain_requires_target_above_zero=False,
        description="造成【高值+15】的所选类型伤害，并恢复所造成总伤害量一半的精神值。",
    ),
    "侵染": SpellDefinition(
        name="侵染",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        status_effect=StatusEffect.POISONED,
        description="对每个被命中的目标施加中毒。",
    ),
    "抢攻": SpellDefinition(
        name="抢攻",
        mp_cost=20,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.IMMEDIATE_ATTACK,
        attributes=["INS", "WLP"],
        immediate_attack=True,
        description="目标可以立刻使用装备武器进行一次顺势攻击；NPC改为使用基础攻击。",
    ),
    "暴怒": SpellDefinition(
        name="暴怒",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        defense_type="magic",
        status_effect=StatusEffect.ENRAGED,
        description="对每个被命中的目标施加激怒。",
    ),
    "硬壳": SpellDefinition(
        name="硬壳",
        mp_cost=10,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.AFFINITY_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        affinity_changes={"physical": Affinity.RESIST},
        description="施法者对物理伤害获得抵抗相性，持续至场景结束。",
    ),
    "战吼": SpellDefinition(
        name="战吼",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.CHECK_BONUS,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        check_bonus=1,
        description="每个目标的命中检定获得+1修正，持续至场景结束。",
    ),
    "削弱": SpellDefinition(
        name="削弱",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE_VULNERABILITY,
        attributes=["INS", "WLP"],
        requires_check=True,
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=(
            "physical",
            "wind",
            "lightning",
            "dark",
            "earth",
            "fire",
            "ice",
            "light",
            "poison",
        ),
        incoming_damage_bonus=5,
        description="所选类型的伤害来源对目标额外造成5点伤害，持续至场景结束。",
    ),
}

# Named spells printed on the core bestiary sheets (pp. 324-353).  They stay
# outside player spell schools, but are first-class rule definitions so an NPC
# can actually use its inherited sheet instead of dropping back to prose.
BESTIARY_NPC_SPELLS: dict[str, SpellDefinition] = {
    "呕吐南瓜": SpellDefinition(
        name="呕吐南瓜",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE_VULNERABILITY,
        attributes=["MIG", "WLP"],
        requires_check=True,
        defense_type="magic",
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("poison",),
        incoming_damage_bonus=5,
        description="毒系伤害来源对目标额外造成5点伤害，持续至场景结束。",
    ),
    "集结嚎叫": SpellDefinition(
        name="集结嚎叫",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.CHECK_BONUS,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        check_bonus=1,
        description="目标的命中检定获得+1修正，持续至场景结束。",
    ),
    "舞动小丑": SpellDefinition(
        name="舞动小丑",
        mp_cost=20,
        target=SpellTarget.ALL_ENEMIES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        status_effect=StatusEffect.SLOW,
        automatic_effect=True,
        mp_cost_per_target=False,
        description="对能看见的所有敌人施加迟缓。",
    ),
    "碎石弹幕": SpellDefinition(
        name="碎石弹幕",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="earth",
        status_effect=StatusEffect.DAZED,
        apply_status_on_success=True,
        description="造成【高值+15】土系伤害，并施加眩晕。",
    ),
    "孢子之息": SpellDefinition(
        name="孢子之息",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="poison",
        status_effect=StatusEffect.WEAKENED,
        apply_status_on_success=True,
        description="造成【高值+15】毒系伤害，并施加虚弱。",
    ),
    "藤蔓暴生": SpellDefinition(
        name="藤蔓暴生",
        mp_cost=20,
        target=SpellTarget.ALL_ENEMIES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        status_effect=StatusEffect.SHAKEN,
        automatic_effect=True,
        mp_cost_per_target=False,
        description="对能看见的所有敌人施加动摇。",
    ),
    "硬化躯壳": SpellDefinition(
        name="硬化躯壳",
        mp_cost=10,
        target=SpellTarget.SELF,
        effect_type=SpellEffectType.AFFINITY_BUFF,
        attributes=["INS", "WLP"],
        duration=EffectTiming.SCENE_END,
        affinity_changes={"physical": Affinity.RESIST},
        description="对物理伤害获得抵抗相性，持续至场景结束。",
    ),
    "余烬之息": SpellDefinition(
        name="余烬之息",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="fire",
        status_effect=StatusEffect.WEAKENED,
        apply_status_on_success=True,
        description="造成【高值+15】火系伤害，并施加虚弱。",
    ),
    "悲丧厉嚎": SpellDefinition(
        name="悲丧厉嚎",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["MIG", "WLP"],
        status_effect=StatusEffect.SHAKEN,
        description="对目标施加动摇。",
    ),
    "化脑术": SpellDefinition(
        name="化脑术",
        mp_cost=5,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.MP_DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=10,
        description="每个被命中的目标失去【高值+10】精神值。",
    ),
    "纠缠": SpellDefinition(
        name="纠缠",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["INS", "WLP"],
        status_effect=StatusEffect.SLOW,
        description="对目标施加迟缓。",
    ),
    "静电波": SpellDefinition(
        name="静电波",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="lightning",
        status_effect=StatusEffect.SLOW,
        apply_status_on_success=True,
        description="造成【高值+15】雷系伤害，并施加迟缓。",
    ),
    "飞叶漩涡": SpellDefinition(
        name="飞叶漩涡",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=10,
        damage_type="physical",
        description="造成【高值+10】物理伤害。",
    ),
    "霜风吐息": SpellDefinition(
        name="霜风吐息",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="ice",
        status_effect=StatusEffect.WEAKENED,
        apply_status_on_success=True,
        description="造成【高值+15】冰系伤害，并施加虚弱。",
    ),
    "岩石弹幕": SpellDefinition(
        name="岩石弹幕",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="earth",
        status_effect=StatusEffect.DAZED,
        apply_status_on_success=True,
        description="造成【高值+15】土系伤害，并施加眩晕。",
    ),
    "恶臭之息": SpellDefinition(
        name="恶臭之息",
        mp_cost=5,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=10,
        damage_type="poison",
        description="造成【高值+10】毒系伤害。",
    ),
    "蜂之舞": SpellDefinition(
        name="蜂之舞",
        mp_cost=20,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.IMMEDIATE_ATTACK,
        attributes=["INS", "WLP"],
        immediate_attack=True,
        description="目标立即进行一次顺势攻击。",
    ),
    "热量控制": SpellDefinition(
        name="热量控制",
        mp_cost=15,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE_VULNERABILITY,
        attributes=["INS", "WLP"],
        requires_check=True,
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("fire", "ice"),
        incoming_damage_bonus=5,
        description="选择火系或冰系；该类型伤害对目标额外造成5点伤害。",
    ),
    "毒雾": SpellDefinition(
        name="毒雾",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["MIG", "WLP"],
        status_effect=StatusEffect.POISONED,
        description="对每个被命中的目标施加中毒。",
    ),
    "弹弹舞": SpellDefinition(
        name="弹弹舞",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.HEAL,
        attributes=["INS", "WLP"],
        fixed_damage=30,
        selectable_statuses=(
            StatusEffect.SLOW,
            StatusEffect.SHAKEN,
            StatusEffect.WEAKENED,
            StatusEffect.DAZED,
            StatusEffect.ENRAGED,
            StatusEffect.POISONED,
        ),
        clear_selected_status=True,
        description="恢复生命值，并解除施法者选择的一项异常状态。",
    ),
    "龙息": SpellDefinition(
        name="龙息",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="fire",
        status_effect=StatusEffect.SHAKEN,
        apply_status_on_success=True,
        description="造成【高值+15】火系伤害，并施加动摇。",
    ),
    "毁灭凝视": SpellDefinition(
        name="毁灭凝视",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.STATUS_APPLY,
        attributes=["MIG", "WLP"],
        selectable_statuses=(StatusEffect.DAZED, StatusEffect.WEAKENED),
        selectable_status_count=2,
        description="对目标施加眩晕和虚弱。",
    ),
    "孢子喷吐": SpellDefinition(
        name="孢子喷吐",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="poison",
        status_effect=StatusEffect.DAZED,
        apply_status_on_success=True,
        description="造成【高值+15】毒系伤害，并施加眩晕。",
    ),
    "水分榨取": SpellDefinition(
        name="水分榨取",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="poison",
        drain_to="hp",
        drain_requires_target_above_zero=False,
        description="造成【高值+15】毒系伤害，并恢复所造成伤害量一半的生命值。",
    ),
    "麻痹气体": SpellDefinition(
        name="麻痹气体",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.MP_DAMAGE,
        attributes=["MIG", "WLP"],
        resource_fraction_loss=0.5,
        description="每个被命中的目标失去当前精神值的一半。",
    ),
    "预消化": SpellDefinition(
        name="预消化",
        mp_cost=10,
        target=SpellTarget.ONE_CREATURE,
        effect_type=SpellEffectType.DAMAGE_VULNERABILITY,
        attributes=["MIG", "WLP"],
        requires_check=True,
        duration=EffectTiming.SCENE_END,
        selectable_damage_types=("physical",),
        incoming_damage_bonus=5,
        description="物理伤害来源对目标额外造成5点伤害。",
    ),
    "腐臭之息": SpellDefinition(
        name="腐臭之息",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["MIG", "WLP"],
        fixed_damage=15,
        damage_type="dark",
        status_effect=StatusEffect.WEAKENED,
        apply_status_on_success=True,
        description="造成【高值+15】暗系伤害，并施加虚弱。",
    ),
    "骷髅影袭": SpellDefinition(
        name="影袭",
        mp_cost=10,
        target=SpellTarget.UP_TO_THREE_CREATURES,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="dark",
        status_effect=StatusEffect.SHAKEN,
        description="造成【高值+15】暗系伤害；机会：对每个目标施加动摇。",
    ),
    "凄厉亡嚎": SpellDefinition(
        name="凄厉亡嚎",
        mp_cost=10,
        target=SpellTarget.ONE_ENEMY,
        effect_type=SpellEffectType.DAMAGE,
        attributes=["INS", "WLP"],
        fixed_damage=15,
        damage_type="ice",
        status_effect=StatusEffect.SHAKEN,
        apply_status_on_success=True,
        description="造成【高值+15】冰系伤害，并施加动摇。",
    ),
}

NPC_SPELLS.update(BESTIARY_NPC_SPELLS)

SPELLS.update(NPC_SPELLS)

SPELL_SCHOOLS: dict[str, tuple[str, ...]] = {
    "元素使法术": (
        "元素幕障",
        "元素武器",
        "焰流",
        "闪电击",
        "寒霜术",
        "冰山术",
        "炎弹",
        "翱翔击",
        "地动",
        "雷霆击",
        "罡风",
        "气旋",
        "巨岩",
    ),
    "熵术士法术": (
        "加速术",
        "扭曲性状",
        "黑暗武器",
        "驱散魔法",
        "预言术",
        "精神汲取",
        "活力汲取",
        "无常命运",
        "镜面反射",
        "终焉降临",
        "时空静滞",
        "影袭",
    ),
    "御魂使法术": (
        "护卫灵气",
        "觉醒",
        "屏障",
        "净化",
        "激怒",
        "幻觉",
        "治愈术",
        "光耀术",
        "慈悲",
        "巩固",
        "灵魂之幕",
        "魂能武器",
        "怠惰",
    ),
}

SPELL_SCHOOL_ALIASES: dict[str, str] = {
    "元素使": "元素使法术",
    "元素魔法": "元素使法术",
    "元素法术": "元素使法术",
    "元素使法术": "元素使法术",
    "熵术士": "熵术士法术",
    "熵系魔法": "熵术士法术",
    "熵系法术": "熵术士法术",
    "控熵学派": "熵术士法术",
    "熵术士法术": "熵术士法术",
    "御魂使": "御魂使法术",
    "灵魂魔法": "御魂使法术",
    "灵魂法术": "御魂使法术",
    "御魂系法术": "御魂使法术",
    "御魂使法术": "御魂使法术",
}

SPELL_ALIASES: dict[str, str] = {
    "雷电术": "电流术",
    "闪电术": "电流术",
    "雷电魔法": "电流术",
    "雷击": "落雷",
    "落雷术": "落雷",
    "火球术": "火焰弹",
    "火焰术": "火焰弹",
    "元素防护罩": "元素幕障",
    "Elemental Shroud": "元素幕障",
    "照明烈焰": "焰流",
    "Flare": "焰流",
    "电流术": "闪电击",
    "Fulgur": "闪电击",
    "冰川覆裂": "寒霜术",
    "Glacies": "寒霜术",
    "冰冻堡垒": "冰山术",
    "Iceberg": "冰山术",
    "伊格尼斯之火": "炎弹",
    "Ignis": "炎弹",
    "大地震击": "地动",
    "Terra": "地动",
    "雷霆": "雷霆击",
    "雷霆术": "雷霆击",
    "Thunderbolt": "雷霆击",
    "烈风": "罡风",
    "Ventus": "罡风",
    "飞天打击": "翱翔击",
    "Soaring Strike": "翱翔击",
    "旋涡": "气旋",
    "Vertex": "气旋",
    "加速": "加速术",
    "Acceleration": "加速术",
    "反常": "扭曲性状",
    "Anomaly": "扭曲性状",
    "消除": "驱散魔法",
    "Dispel": "驱散魔法",
    "预测": "预言术",
    "Divination": "预言术",
    "抽取精魂": "精神汲取",
    "Drain Spirit": "精神汲取",
    "抽取活力": "活力汲取",
    "Drain Vigor": "活力汲取",
    "赌博": "无常命运",
    "Gamble": "无常命运",
    "魔镜": "镜面反射",
    "Mirror": "镜面反射",
    "欧米茄终结": "终焉降临",
    "Omega": "终焉降临",
    "停滞": "时空静滞",
    "Stop": "时空静滞",
    "半影": "影袭",
    "Umbra": "影袭",
    "光环": "护卫灵气",
    "Aura": "护卫灵气",
    "护盾": "屏障",
    "Barrier": "屏障",
    "治愈": "治愈术",
    "Heal": "治愈术",
    "光照射线": "光耀术",
    "Lux": "光耀术",
    "加强": "巩固",
    "Reinforce": "巩固",
    "灵魂武器": "魂能武器",
    "Soul Weapon": "魂能武器",
    "迟钝": "怠惰",
    "Torpor": "怠惰",
}


def get_spell_definition(name: str) -> SpellDefinition:
    name = normalize_spell_name(name)
    try:
        return SPELLS[name]
    except KeyError as exc:
        raise ValueError(f"未找到法术定义：{name}") from exc


def normalize_spell_name(name: str) -> str:
    clean = str(name or "").strip()
    return SPELL_ALIASES.get(clean, clean)


def canonical_spell_names() -> tuple[str, ...]:
    """Return player-facing rulebook spell names without deprecated aliases."""

    names: list[str] = []
    seen: set[str] = set()
    for school_names in SPELL_SCHOOLS.values():
        for name in school_names:
            canonical = normalize_spell_name(name)
            if canonical not in seen:
                seen.add(canonical)
                names.append(canonical)
    return tuple(names)


def spell_matching_candidates(*, include_aliases: bool = True) -> tuple[str, ...]:
    """Names that can be recognized from player text, sorted longest first."""

    names = set(canonical_spell_names())
    if include_aliases:
        names.update(SPELL_ALIASES)
    return tuple(sorted(names, key=len, reverse=True))


def normalize_spell_school(school: str) -> str:
    clean = str(school or "").strip()
    return SPELL_SCHOOL_ALIASES.get(clean, clean)


def is_known_spell(name: str) -> bool:
    return normalize_spell_name(name) in SPELLS


def spell_school_for(name: str) -> str:
    canonical = normalize_spell_name(name)
    for school, names in SPELL_SCHOOLS.items():
        if canonical in names:
            return school
    return ""


def spell_names_for_school(school: str) -> tuple[str, ...]:
    return SPELL_SCHOOLS.get(normalize_spell_school(school), ())
